planning

diff --git a/master/static/srv/agent_setup_script.sh.template b/master/static/srv/agent_setup_script.sh.template
--- a/master/static/srv/agent_setup_script.sh.template
+++ b/master/static/srv/agent_setup_script.sh.template
@@ -8,7 +8,10 @@ echo "#### PRINTING STARTUP SCRIPT START ####"
 cat /usr/local/determined/startup_script
 echo "#### PRINTING STARTUP SCRIPT END ####"
 chmod +x /usr/local/determined/startup_script
+# TODO: fail if this fails
+set -e
 /usr/local/determined/startup_script
+set +e
 
 echo {{.ConfigFileBase64}} | base64 --decode >/usr/local/determined/agent.yaml
 echo "#### PRINTING CONFIG FILE START ####"
